# netlify.toml
# This file configures Netlify for your site and functions.

[build]
  # Specifies the directory where your build output (your frontend files) is located.
  # Since index.html is inside the 'public' folder, we set publish to "public".
  publish = "public" 

  # Specifies the directory where your Netlify Functions are located.
  # This path is relative to the root of your repository.
  functions = "netlify/functions"

# You can add more configurations here if needed.
